<div id="menu_wrap">
            <nav class="menu">
                <ul class="nav_list">
                    <li>
                        <a href="#">
                            GALLERY
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            SUNGLASSES
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            GLASSES
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            EVENT
                        </a>
                    </li>
                </ul>
            </nav>
        </div>