<div id="header">
            <header class="wrap">
                <h1 class="logo">
                    <a href="/">
                        <img src="images/logo_white.png" alt="로고">
                    </a>
                </h1>
                <ul class="gnb">
                    <li>
                        <a href="#">
                            <img src="images/icon_bag_white.png" alt="장바구니">
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <img src="images/icon_heart_white.png" alt="관심상품">
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <img src="images/icon_search_white.png" alt="검색">
                        </a>
                    </li>
                    <li>
                        <a href="#" class="menu_btn">
                            <img src="images/icon_menu_white.png" alt="메뉴">
                        </a>
                    </li>
                </ul>
            </header>
        </div>